import scrapA from './scrapers/scrapA.js';
import scrapE from './scrapers/scrapE.js';
import scrapG from './scrapers/scrapG.js';
import scrapH from './scrapers/scrapH.js';
import scrapT from './scrapers/scrapT.js';
import scrapVC from './scrapers/scrapVC.js';
import scrapP from './scrapers/scrapP.js';

const config = {
  e: {
    channel: process.env.E_CHANNEL,
    url: process.env.E_URL,
    scraper: scrapE,
  },
  g: {
    channel: process.env.G_CHANNEL,
    url: process.env.G_URL,
    scraper: scrapG,
  },
  ge: {
    channel: process.env.GE_CHANNEL,
    url: process.env.GE_URL,
    scraper: scrapG,
  },
  gb: {
    channel: process.env.GB_CHANNEL,
    url: process.env.GB_URL,
    scraper: scrapG,
  },
  h: {
    channel: process.env.H_CHANNEL,
    url: process.env.H_URL,
    scraper: scrapH,
  },
  t: {
    channel: process.env.T_CHANNEL,
    url: process.env.T_URL,
    scraper: scrapT,
  },
  a: {
    channel: process.env.A_CHANNEL,
    url: process.env.A_URL,
    scraper: scrapA,
  },
  p: {
    channel: process.env.P_CHANNEL,
    url: process.env.P_URL,
    scraper: scrapP,
  },

  vc: {
    channel: process.env.VC_CHANNEL,
    url: process.env.VC_URL,
    scraper: scrapVC,
    role: process.env.VC_ROLE,
    emoji: process.env.VC_EMOJI,
  },
  vc0: {
    channel: process.env.VC0_CHANNEL,
    url: process.env.VC0_URL,
    scraper: scrapVC,
    role: process.env.VC0_ROLE,
    emoji: process.env.VC0_EMOJI,
  },
  vc1: {
    channel: process.env.VC1_CHANNEL,
    url: process.env.VC1_URL,
    scraper: scrapVC,
    role: process.env.VC1_ROLE,
    emoji: process.env.VC1_EMOJI,
  },
  vc2: {
    channel: process.env.VC2_CHANNEL,
    url: process.env.VC2_URL,
    scraper: scrapVC,
    role: process.env.VC2_ROLE,
    emoji: process.env.VC2_EMOJI,
  },
  vc3: {
    channel: process.env.VC3_CHANNEL,
    url: process.env.VC3_URL,
    scraper: scrapVC,
    role: process.env.VC3_ROLE,
    emoji: process.env.VC3_EMOJI,
  },
  vc4: {
    channel: process.env.VC4_CHANNEL,
    url: process.env.VC4_URL,
    scraper: scrapVC,
    role: process.env.VC4_ROLE,
    emoji: process.env.VC4_EMOJI,
  },
  vc5: {
    channel: process.env.VC5_CHANNEL,
    url: process.env.VC5_URL,
    scraper: scrapVC,
    role: process.env.VC5_ROLE,
    emoji: process.env.VC5_EMOJI,
  },
  vc6: {
    channel: process.env.VC6_CHANNEL,
    url: process.env.VC6_URL,
    scraper: scrapVC,
    role: process.env.VC6_ROLE,
    emoji: process.env.VC6_EMOJI,
  },
  vc7: {
    channel: process.env.VC7_CHANNEL,
    url: process.env.VC7_URL,
    scraper: scrapVC,
    role: process.env.VC7_ROLE,
    emoji: process.env.VC7_EMOJI,
  },
  vc8: {
    channel: process.env.VC8_CHANNEL,
    url: process.env.VC8_URL,
    scraper: scrapVC,
    role: process.env.VC8_ROLE,
    emoji: process.env.VC8_EMOJI,
  },
  vc9: {
    channel: process.env.VC9_CHANNEL,
    url: process.env.VC9_URL,
    scraper: scrapVC,
    role: process.env.VC9_ROLE,
    emoji: process.env.VC9_EMOJI,
  },
  vc10: {
    channel: process.env.VC10_CHANNEL,
    url: process.env.VC10_URL,
    scraper: scrapVC,
    role: process.env.VC10_ROLE,
    emoji: process.env.VC10_EMOJI,
  },
  vc11: {
    channel: process.env.VC11_CHANNEL,
    url: process.env.VC11_URL,
    scraper: scrapVC,
    role: process.env.VC11_ROLE,
    emoji: process.env.VC11_EMOJI,
  },
  vc12: {
    channel: process.env.VC12_CHANNEL,
    url: process.env.VC12_URL,
    scraper: scrapVC,
    role: process.env.VC12_ROLE,
    emoji: process.env.VC12_EMOJI,
  },
  vc13: {
    channel: process.env.VC13_CHANNEL,
    url: process.env.VC13_URL,
    scraper: scrapVC,
    role: process.env.VC13_ROLE,
    emoji: process.env.VC13_EMOJI,
  },
  vc14: {
    channel: process.env.VC14_CHANNEL,
    url: process.env.VC14_URL,
    scraper: scrapVC,
    role: process.env.VC14_ROLE,
    emoji: process.env.VC14_EMOJI,
  },
  vc15: {
    channel: process.env.VC15_CHANNEL,
    url: process.env.VC15_URL,
    scraper: scrapVC,
    role: process.env.VC15_ROLE,
    emoji: process.env.VC15_EMOJI,
  },
  vc16: {
    channel: process.env.VC16_CHANNEL,
    url: process.env.VC16_URL,
    scraper: scrapVC,
    role: process.env.VC16_ROLE,
    emoji: process.env.VC16_EMOJI,
  },
  vc17: {
    channel: process.env.VC17_CHANNEL,
    url: process.env.VC17_URL,
    scraper: scrapVC,
    role: process.env.VC17_ROLE,
    emoji: process.env.VC17_EMOJI,
  },
  vc18: {
    channel: process.env.VC18_CHANNEL,
    url: process.env.VC18_URL,
    scraper: scrapVC,
    role: process.env.VC18_ROLE,
    emoji: process.env.VC18_EMOJI,
  },
  vc19: {
    channel: process.env.VC19_CHANNEL,
    url: process.env.VC19_URL,
    scraper: scrapVC,
    role: process.env.VC19_ROLE,
    emoji: process.env.VC19_EMOJI,
  },
  vc20: {
    channel: process.env.VC20_CHANNEL,
    url: process.env.VC20_URL,
    scraper: scrapVC,
    role: process.env.VC20_ROLE,
    emoji: process.env.VC20_EMOJI,
  },
  vc21: {
    channel: process.env.VC21_CHANNEL,
    url: process.env.VC21_URL,
    scraper: scrapVC,
    role: process.env.VC21_ROLE,
    emoji: process.env.VC21_EMOJI,
  },
  vc22: {
    channel: process.env.VC22_CHANNEL,
    url: process.env.VC22_URL,
    scraper: scrapVC,
    role: process.env.VC22_ROLE,
    emoji: process.env.VC22_EMOJI,
  },
  vc23: {
    channel: process.env.VC23_CHANNEL,
    url: process.env.VC23_URL,
    scraper: scrapVC,
    role: process.env.VC23_ROLE,
    emoji: process.env.VC23_EMOJI,
  },
  vc24: {
    channel: process.env.VC24_CHANNEL,
    url: process.env.VC24_URL,
    scraper: scrapVC,
    role: process.env.VC24_ROLE,
    emoji: process.env.VC24_EMOJI,
  },
  vc25: {
    channel: process.env.VC25_CHANNEL,
    url: process.env.VC25_URL,
    scraper: scrapVC,
    role: process.env.VC25_ROLE,
    emoji: process.env.VC25_EMOJI,
  },
  vc26: {
    channel: process.env.VC26_CHANNEL,
    url: process.env.VC26_URL,
    scraper: scrapVC,
    role: process.env.VC26_ROLE,
    emoji: process.env.VC26_EMOJI,
  },
  vc27: {
    channel: process.env.VC27_CHANNEL,
    url: process.env.VC27_URL,
    scraper: scrapVC,
    role: process.env.VC27_ROLE,
    emoji: process.env.VC27_EMOJI,
  },
};

export default config;
